USERNAME                   = 'jrl44'
LOCAL_TO_REMOTE_KEY_FILE   = '~/.ssh/jrl44sagarmatha2fear'
REMOTE_TO_LOCAL_KEY_FILE   = '/users/jrl44/.ssh/jrl44fear2sagarmatha'
REMOTE_TEMP_PATH           = '/users/jrl44/temp'
REMOTE_PYTHON_PATH         = '/users/jrl44/python'
REMOTE_MATLAB_PATH         = '/users/jrl44/matlab'
LOCAL_TEMP_PATH            = '~/temp'
LOCAL_HOST                 = 'sagarmatha'
